name: solar system workflow

on:
    push:
        branches:
        - main

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up NodeJs
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Unit testing
              run: npm test

        